name: tcga-brca-ml
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - statsmodels
  - joblib
  - fastapi
  - uvicorn
  - httpx
  - jupyterlab
  - pytest
  - pip
  - pip:
      - gprofiler-official
